//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormsTrackR1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblAzureNHPushRegistration
    {
        public int Id { get; set; }
        public int AccountId { get; set; }
        public int AzurePushSlot_Number { get; set; }
        public int Device_Registrations { get; set; }
        public int App_Id { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
    }
}
