//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormsTrackR1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblAccountDetail
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string AccountName { get; set; }
        public string Description { get; set; }
        public string Address { get; set; }
        public string Address1 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string ZipCode { get; set; }
        public string Logo { get; set; }
        public string Phone { get; set; }
        public int TimeZone { get; set; }
        public int FormDraftTime { get; set; }
        public int SubscriptionId { get; set; }
        public System.DateTime RenewalDate { get; set; }
        public int SubscriptionPeriod { get; set; }
        public string SubscriptionJson { get; set; }
        public string SubscriptionUsageJson { get; set; }
        public int SalesPersonId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public string DashBoardSettings { get; set; }
        public Nullable<int> DisplayOrderType { get; set; }
        public decimal RenewalAmount { get; set; }
        public bool IsFirstLogin { get; set; }
        public string CountryCode { get; set; }
        public Nullable<int> DisplayOrderTypeQr { get; set; }
        public bool IsTestAccount { get; set; }
        public int DisplayOrderTypeForms { get; set; }
        public Nullable<System.DateTime> LastSubscriptionDate { get; set; }
    }
}
