//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormsTrackR1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblApplicationTimeZone
    {
        public int Id { get; set; }
        public string DisplayName { get; set; }
        public string DisplayValue { get; set; }
        public int WebHours { get; set; }
        public int WebMins { get; set; }
        public int AppHours { get; set; }
        public int AppMins { get; set; }
        public string Country { get; set; }
        public string TimeZoneId { get; set; }
    }
}
