//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormsTrackR1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblButtonRespons
    {
        public int Id { get; set; }
        public int AccountId { get; set; }
        public int QRCodeId { get; set; }
        public Nullable<int> BDID { get; set; }
        public string Message { get; set; }
        public string ImagePath { get; set; }
        public string ContactName { get; set; }
        public string ContactEmail { get; set; }
        public string ContactPhoneNumber { get; set; }
        public string DeviceGPSDetails { get; set; }
        public string CurrentLocation { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public Nullable<int> ZipCode { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> UserModuleId { get; set; }
        public Nullable<decimal> ProximityDistance { get; set; }
        public string ProximityStatus { get; set; }
        public string Notes { get; set; }
        public bool IsQRCodeScan { get; set; }
        public bool IsApproximateDistance { get; set; }
        public bool IsRead { get; set; }
        public bool IsArchive { get; set; }
        public bool IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public int UserId { get; set; }
        public bool IsPredefined { get; set; }
        public string DeviceType { get; set; }
    }
}
