//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormsTrackR1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblFormTransaction
    {
        public int Id { get; set; }
        public int FormPage { get; set; }
        public int TransactionId { get; set; }
        public int QRCodeId { get; set; }
        public int AccountId { get; set; }
        public int UserModuleId { get; set; }
        public int ReferenceId { get; set; }
        public int ResponseId { get; set; }
        public int FormId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
    }
}
