//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormsTrackR1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblForm
    {
        public int Id { get; set; }
        public int AccountId { get; set; }
        public int UserId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Keywords { get; set; }
        public string FormControllersJson { get; set; }
        public string FormElementsJson { get; set; }
        public int CategoryId { get; set; }
        public int SubmissionCount { get; set; }
        public string UsageModulesJson { get; set; }
        public int IsDraftEnabled { get; set; }
        public int IsSubmissionAllowedByAll { get; set; }
        public int IsReminderEnabled { get; set; }
        public int IsActive { get; set; }
        public int IsTemplate { get; set; }
        public string TemplateCategory { get; set; }
        public string FormElementsJsonGroup { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public string MaxElement { get; set; }
        public int FormPagesCount { get; set; }
        public int OrderNumber { get; set; }
    }
}
