//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormsTrackR1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblFormResponseReport
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string FormIds { get; set; }
        public string QRButtonIds { get; set; }
        public string CategoryIds { get; set; }
        public string IncludedColumns { get; set; }
        public string LinkedQRReports { get; set; }
        public string NotificationObj { get; set; }
        public string CustomizeReportFormatObj { get; set; }
        public Nullable<bool> IsFavorite { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public string BusinessRulesObj { get; set; }
        public string FormulasObj { get; set; }
        public string IfElseObj { get; set; }
        public string ScheduleReportObj { get; set; }
        public int AccountId { get; set; }
        public int UserId { get; set; }
        public string DisplayHeaderType { get; set; }
        public bool isReportPreview { get; set; }
        public Nullable<int> OrderNumber { get; set; }
        public Nullable<int> isReportQueue { get; set; }
        public Nullable<int> RandomNumber { get; set; }
        public string ReportPreviewCustomFields { get; set; }
        public Nullable<int> ErrorCount { get; set; }
        public string NextRunDate { get; set; }
        public Nullable<System.DateTime> LastRunDate { get; set; }
        public int ModuleId { get; set; }
    }
}
