//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormsTrackR1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblFormRespons
    {
        public int Id { get; set; }
        public Nullable<int> ReferenceId { get; set; }
        public int QRCodeId { get; set; }
        public int FormId { get; set; }
        public int AccountId { get; set; }
        public int UserId { get; set; }
        public string QRCodeTitle { get; set; }
        public string FormTitle { get; set; }
        public string DeviceType { get; set; }
        public string OSType { get; set; }
        public string CategoryName { get; set; }
        public string CustomFields { get; set; }
        public string AssociateIdsWithAccess { get; set; }
        public string Notes { get; set; }
        public string BDID { get; set; }
        public string Reminder { get; set; }
        public Nullable<int> ReminderParentResponseID { get; set; }
        public bool IsRead { get; set; }
        public bool IsBlocked { get; set; }
        public bool IsArchived { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsPublic { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public string FormResponseJson { get; set; }
        public string StatusJson { get; set; }
        public Nullable<int> AssignedUserId { get; set; }
        public string Status { get; set; }
        public string AppVersion { get; set; }
    }
}
