//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormsTrackR1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblLabelTemplate
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string DesignObject { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<int> ModuleId { get; set; }
        public string Height { get; set; }
        public string Width { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public bool IsRotate { get; set; }
        public string TemplateDesignObject { get; set; }
        public int CategoryId { get; set; }
    }
}
