//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormsTrackR1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMasterPermission
    {
        public int Id { get; set; }
        public string PermissionTitle { get; set; }
        public string PermissionType { get; set; }
        public bool isActive { get; set; }
        public string PermissionSubType { get; set; }
        public int DisplayOrder { get; set; }
        public string FormsTrackRId { get; set; }
        public string ToolTip { get; set; }
    }
}
