//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormsTrackR1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblNotification
    {
        public int Id { get; set; }
        public string NotificationType { get; set; }
        public string NotificationText { get; set; }
        public string Source { get; set; }
        public System.DateTime SentDate { get; set; }
        public int UserId { get; set; }
        public int AccountId { get; set; }
        public int Status { get; set; }
        public bool IsActive { get; set; }
        public string Contacts { get; set; }
        public string SentDeviceIds { get; set; }
        public string Devices { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
    }
}
