//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormsTrackR1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblPermission
    {
        public int Id { get; set; }
        public Nullable<int> MappingId { get; set; }
        public string AdminPermissions { get; set; }
        public string AppPermissions { get; set; }
        public string QrButtonPermissions { get; set; }
        public string FormResponsePermissions { get; set; }
        public string FormNotificationsPermissions { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public bool IsActive { get; set; }
        public int AccountId { get; set; }
        public int MappingType { get; set; }
        public string ModulePermissions { get; set; }
    }
}
