//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormsTrackR1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblQRCode
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public int Type { get; set; }
        public int ModuleId { get; set; }
        public int OrderNumber { get; set; }
        public string QRCodePath { get; set; }
        public int CategoryId { get; set; }
        public bool IsTemplate { get; set; }
        public int DaysSinceLastScan { get; set; }
        public string ShareLink { get; set; }
        public bool IsActive { get; set; }
        public int AccountId { get; set; }
        public int UserId { get; set; }
        public Nullable<System.DateTime> LastScannedDate { get; set; }
        public int ScannedCount { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public string ArchivalPrefsJson { get; set; }
        public string BasicConfigJson { get; set; }
        public string CustomFieldsJson { get; set; }
        public string DataCaptureJson { get; set; }
        public string HubConnectPrefsJson { get; set; }
        public string LinkedReportsJson { get; set; }
        public string NotificationPrefsJson { get; set; }
        public string Base64Image { get; set; }
    }
}
