//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormsTrackR1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblReplyMessageHistory
    {
        public int Id { get; set; }
        public int HistoryId { get; set; }
        public string Notes { get; set; }
        public string ReplyEmailIds { get; set; }
        public string NotesBy { get; set; }
        public string ButtonType { get; set; }
        public bool IsSender { get; set; }
        public string DeviceType { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public string Status { get; set; }
    }
}
