//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormsTrackR1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblUsersDeviceInfo
    {
        public int Id { get; set; }
        public int AccountId { get; set; }
        public string PushTokenId { get; set; }
        public string Device_Type { get; set; }
        public string UniqueDeviceId { get; set; }
        public Nullable<System.DateTime> LastAccessed_Date { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> MuteStartTime { get; set; }
        public Nullable<System.DateTime> MuteEndTime { get; set; }
        public bool IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
    }
}
